let today = new Date();
console.log(today)
console.log(today.getDay())
console.log(today.getDate())
console.log(today.getMonth())
console.log(today.getFullYear())
console.log(today.getHours())
console.log(today.getMinutes())
console.log(today.getSeconds())
console.log(today.getTime())
console.log("------------------------------")

let Days = new Date(2022,3,11,22,15,23);
console.log(Days)
console.log(Days.getDay())
console.log(Days.getDate())
console.log(Days.getMonth())
console.log(Days.getFullYear())
console.log(Days.getHours())
console.log(Days.getMinutes())
console.log(Days.getSeconds())
console.log(Days.getTime())
console.log("------------------------------")

let DayTest = new Date("2022/5/25 12:53:0");
console.log(DayTest)
console.log(DayTest.getDay())
console.log(DayTest.getDate())
console.log(DayTest.getMonth())
console.log(DayTest.getFullYear())
console.log(DayTest.getHours())
console.log(DayTest.getMinutes())
console.log(DayTest.getSeconds())
console.log(DayTest.getTime())
